In [1]:
import tensorflow as tf
print tf.__version__
sess = tf.InteractiveSession()

1.1.0-rc2


In [2]:
from tensorflow.python.ops import tensor_array_ops, control_flow_ops

In [3]:
from tensorflow.python.framework import dtypes
ta = tensor_array_ops.TensorArray(
      dtype=dtypes.float32,
      tensor_array_name="foo",
      size=3,
      infer_shape=False)

w0 = ta.write(0, [[4.0, 5.0]])
w1 = w0.write(1, [[1.0]])
w2 = w1.write(2, -3.0)

r0 = w2.read(0)
r1 = w2.read(1)
r2 = w2.read(2)

In [4]:
r0.eval()

array([[ 4.,  5.]], dtype=float32)

In [5]:
import numpy as np
tf_dtype = dtypes.float32
dtype = tf_dtype.as_numpy_dtype()
ta = tensor_array_ops.TensorArray(
    dtype=tf_dtype, tensor_array_name="foo", size=3)

if tf_dtype == dtypes.string:
  # In Python3, np.str is unicode, while we always want bytes
  convert = lambda x: np.asarray(x).astype("|S")
else:
  convert = lambda x: np.asarray(x).astype(dtype)

w0 = ta.write(0, convert([[4.0, 5.0]]))
w1 = w0.write(1, convert([[6.0, 7.0]]))
w2 = w1.write(2, convert([[8.0, 9.0]]))


#c0 = w2.stack()
c0 = w2.pack()

In [6]:
c0.eval()

array([[[ 4.,  5.]],

       [[ 6.,  7.]],

       [[ 8.,  9.]]], dtype=float32)

In [7]:
c0.eval().shape

(3, 1, 2)

In [8]:
ta = tensor_array_ops.TensorArray(
    dtype=tf_dtype, tensor_array_name="foo", size=3, infer_shape=False)
w0 = ta.write(0, convert([[4.0, 5.0], [104.0, 105.0], [204.0, 205.0]]))
w1 = w0.write(1, convert([[6.0, 7.0], [106.0, 107.0]]))
w2 = w1.write(2, convert([[8.0, 9.0]]))

c0 = w2.concat()


In [9]:
c0.eval()

array([[   4.,    5.],
       [ 104.,  105.],
       [ 204.,  205.],
       [   6.,    7.],
       [ 106.,  107.],
       [   8.,    9.]], dtype=float32)

In [10]:
c0.eval().shape

(6, 2)

In [11]:
emb = tf.constant([[1, 2, 5, 3], [3, 4, 5, 6]])
x = tf.argmax(emb, 1)

x = tf.expand_dims(x, 0)

In [12]:
ta = tensor_array_ops.TensorArray(
    dtype=tf.int64, tensor_array_name="foo", size=3, infer_shape=False)
w0 = ta.write(0, x)
w1 = w0.write(1, x)
w2 = w1.write(2, x)

c0 = w2.concat()

In [13]:
c0.eval()

array([[2, 3],
       [2, 3],
       [2, 3]])

In [14]:
tf.transpose(c0, [1, 0]).eval()

array([[2, 2, 2],
       [3, 3, 3]])

In [16]:
c1 = w2.stack()
c1.eval()

AttributeError: 'TensorArray' object has no attribute 'stack'

In [15]:
ta = tensor_array_ops.TensorArray(
    dtype=tf.int64, tensor_array_name="foo", dynamic_size=True, infer_shape=False)
w0 = ta.write(0, x)
w1 = w0.write(1, x)
w2 = w1.write(2, x)
w3 = w2.write(2, x)

c0 = w3.concat()
c0.eval()

ValueError: Size must be provided if handle is not provided